// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Trả về version của app. Nguồn duy nhất là `Cargo.toml`
	 *  (`CARGO_PKG_VERSION`, đọc lúc biên dịch) — không có nơi thứ hai giữ version.
	 */
	appVersion: () => typedError<string, AppError>(__TAURI_INVOKE("app_version")),
	/**  Đọc toàn bộ settings hiện tại — xem [`get_settings`] cho logic thật. */
	settingsGet: () => typedError<Settings, AppError>(__TAURI_INVOKE("settings_get")),
	/**
	 *  Ghi toàn bộ settings và phát `settingsChanged` — xem
	 *  [`save_settings_and_notify`] cho logic ghi/thông báo thật; phát event
	 *  thất bại (ví dụ chưa có cửa sổ nào) không làm command trả lỗi vì dữ liệu
	 *  đã ghi bền xong, chỉ log cảnh báo.
	 */
	settingsSave: (settings: Settings) => typedError<null, AppError>(__TAURI_INVOKE("settings_save", { settings })),
	/**
	 *  Return the Rust-owned consent policy and the durable decision in one
	 *  typed snapshot. A policy read failure is a storage error; no fallback
	 *  version is invented in the frontend.
	 */
	consentPolicy: () => typedError<ConsentPolicy, AppError>(__TAURI_INVOKE("consent_policy")),
	/**
	 *  Persist acceptance at the current Rust-owned version and emit the full
	 *  settings snapshot only after the durable write succeeds.
	 */
	consentAccept: (settings: Settings) => typedError<Settings, AppError>(__TAURI_INVOKE("consent_accept", { settings })),
	/**
	 *  Persist a deliberate decline independently from the accepted-version
	 *  field, then emit the same full snapshot contract as settings_save.
	 */
	consentDecline: (settings: Settings) => typedError<Settings, AppError>(__TAURI_INVOKE("consent_decline", { settings })),
	/**  Return only opaque IDs and masked labels; key material never crosses IPC. */
	keysList: () => typedError<KeyMetadata[], AppError>(__TAURI_INVOKE("keys_list")),
	/**
	 *  Replace the complete native-store key list, then refresh the actor before
	 *  replying so no removed key can be allocated after command completion.
	 */
	keysSet: (keys: string) => typedError<KeyMetadata[], AppError>(__TAURI_INVOKE("keys_set", { keys })),
	/**  Delete one native credential entry by opaque ID and invalidate old leases. */
	keysDelete: (id: KeyId) => typedError<KeyMetadata[], AppError>(__TAURI_INVOKE("keys_delete", { id })),
	/**
	 *  List models through the one Gemini gateway. Consent is read server-side
	 *  for every call so a stale frontend snapshot can never open transport.
	 */
	modelsList: (kind: ModelKind) => typedError<ModelInfo[], AppError>(__TAURI_INVOKE("models_list", { kind })),
	/**
	 *  Validate one opaque key ID through a target-key lease. The actor path
	 *  deliberately cannot fall back to another key after a 401/403 or quota.
	 */
	keysTest: (id: KeyId) => typedError<KeyTestResult, AppError>(__TAURI_INVOKE("keys_test", { id })),
	/**
	 *  Đọc bộ đếm cục bộ (phiên, lỗi theo category, crash) cho Settings → Chẩn
	 *  đoán — xem [`diagnostics::summary`] cho logic thật.
	 */
	diagnosticsSummary: () => typedError<DiagnosticsSummary, AppError>(__TAURI_INVOKE("diagnostics_summary")),
	/**
	 *  Xoá nhật ký allow-list: file cũ bị xoá, file hôm nay bị truncate (spec
	 *  Boundaries "Xoá nhật ký") — xem [`diagnostics::clear_logs`].
	 */
	diagnosticsClearLogs: () => typedError<null, AppError>(__TAURI_INVOKE("diagnostics_clear_logs")),
	/**
	 *  Xuất gói chẩn đoán: build bundle (log allow-list + bộ đếm) rồi mở dialog
	 *  lưu hệ thống trong `spawn_blocking` — bản thân dialog chạy trên main
	 *  thread qua [`save_diagnostics_bundle`], `spawn_blocking` ở đây chỉ giữ
	 *  việc chờ kết quả tránh chặn runtime async.
	 */
	diagnosticsExport: () => typedError<boolean, AppError>(__TAURI_INVOKE("diagnostics_export")),
	/**
	 *  Bắt đầu transcribe một file (spec Always: thứ tự gate đầy đủ nằm ở
	 *  [`transcribe_start_inner`]). `path` là đường dẫn tuyệt đối do caller cung
	 *  cấp — story này không mở dialog/nhận kéo thả (2.8/2.9 sẽ gọi lệnh này với
	 *  đường dẫn đã chọn).
	 */
	transcribeStart: (path: string) => typedError<TranscribeStartOutcome, AppError>(__TAURI_INVOKE("transcribe_start", { path })),
	/**
	 *  Đăng ký một Channel nhận snapshot rồi các `JobEvent` tiếp theo (spec
	 *  Always: "snapshot và đăng ký Channel trong cùng một lệnh actor").
	 */
	jobsSubscribe: (onEvent: Channel<JobEvent>) => typedError<null, AppError>(__TAURI_INVOKE("jobs_subscribe", { onEvent })),
	/**
	 *  Huỷ một Job — xem [`crate::transcribe::job::CancelOutcome`] cho ý nghĩa
	 *  kết quả (spec I/O Matrix "Huỷ": "Cancel đến sau commit -> trả kết quả
	 *  hoàn tất").
	 */
	jobsCancel: (jobId: string) => typedError<CancelOutcome, AppError>(__TAURI_INVOKE("jobs_cancel", { jobId })),
	/**  Tra `id` (Job hoặc Phiên) cho route `/session/:id`. */
	librarySessionGet: (id: string) => typedError<SessionLookup, AppError>(__TAURI_INVOKE("library_session_get", { id })),
	/**
	 *  Người dùng xác nhận đóng app khi registry đang bận (spec Design Notes:
	 *  "đồng ý → huỷ sạch rồi thoát"): huỷ mọi Job hiện có, chờ tối đa ~4 s để
	 *  mỗi Job dọn xong (huỷ có hiệu lực ≤ 2 s — spec Always), rồi thoát tiến
	 *  trình thật sự bất kể kết quả chờ, vì người dùng đã đồng ý đóng.
	 */
	appCloseConfirm: () => typedError<null, AppError>(__TAURI_INVOKE("app_close_confirm")),
};

/** Events */
export const events = {
	closeRequested: makeEvent<CloseRequested>("close-requested"),
	settingsChanged: makeEvent<SettingsChanged>("settings-changed"),
};

/* Types */
/**
 *  Lỗi thống nhất trả qua mọi command IPC. Serialize `{ category, code,
 *  detailRedacted }` — spec Boundaries.
 */
export type AppError = {
	category: Category,
	code: Code,
	detailRedacted: string,
};

/**
 *  Trả về từ lệnh `jobs_cancel` — phân biệt "đã bắt đầu huỷ" khỏi "Job không
 *  còn để huỷ" (đã commit, hoặc id không tồn tại — spec I/O Matrix "Huỷ":
 *  "Cancel đến sau commit -> trả kết quả hoàn tất").
 */
export type CancelOutcome = "cancelling" | "alreadyFinished";

/**  8 category ổn định hiển thị cho người dùng — spec Boundaries. */
export type Category = "quota" | "auth" | "model" | "network" | "format" | "permission" | "storage" | "blocked";

/**
 *  Phát khi cửa sổ chính bị yêu cầu đóng trong lúc registry bận (spec Design
 *  Notes: "bận → emit `CloseRequested`") — UI hỏi xác nhận, gọi
 *  `app_close_confirm` nếu người dùng đồng ý huỷ sạch rồi thoát.
 */
export type CloseRequested = null;

/**
 *  Mã lỗi kỹ thuật — 12 biến thể, người dùng chốt 2026-09-22. Ánh xạ
 *  `code → category` chỉ định nghĩa ở [`Code::category`], không lặp lại nơi
 *  khác trong codebase.
 */
export type Code = "quota" | "auth" | "model" | "request" | "shape" | "timeout" | "network" | "tls" | "blocked" | "format" | "permission" | "storage";

/**
 *  Rust-owned metadata needed to render the consent step. The accepted
 *  version and declined bit are included so the frontend never needs a
 *  second source of truth or a duplicated version constant.
 */
export type ConsentPolicy = {
	currentVersion: number,
	privacyUrl: string,
	/**
	 *  Support contact URL for Settings → Giới thiệu (spec Always). Carried
	 *  here (rather than a separate command) so it is already loaded
	 *  whenever `settingsStore` fetches the consent policy — including when
	 *  Consent was declined, when About must still show it (spec Always:
	 *  "Hoạt động cả khi Consent bị từ chối").
	 */
	supportUrl: string,
	acceptedVersion: number,
	declined: boolean,
	status: ConsentStatus,
};

/**  The state used by both routing and the Gemini transport gate. */
export type ConsentStatus = "pending" | "declined" | "stale" | "current";

/**
 *  Snapshot chỉ-số hiển thị ở Settings → Chẩn đoán. Không có trường nào mang
 *  nội dung — chỉ số nguyên (spec Boundaries: "Riêng tư của bộ đếm").
 */
export type DiagnosticsSummary = {
	sessions: number,
	crashes: number,
	errorsByCategory: ErrorCategoryCount[],
};

export type ErrorCategoryCount = {
	category: Category,
	count: number,
};

/**
 *  Một event của registry — mỗi biến thể mang riêng `seq: u32`, một bộ đếm
 *  đơn điệu dùng chung cho toàn bộ registry, không phải theo từng Job (spec
 *  Always: "`seq: u32` đơn điệu cho cả registry").
 */
export type JobEvent = 
/**
 *  Toàn bộ Job hiện có trong registry — gửi riêng cho một Channel mới
 *  đăng ký ngay khi `jobs_subscribe` được gọi, trước mọi event khác của
 *  đúng Channel đó (spec I/O Matrix "Remount UI").
 */
{ kind: "snapshot"; seq: number; jobs: JobSnapshot[] } | 
/**  Một Job (đang chờ hoặc đang chạy) vừa đổi trạng thái hiển thị. */
{ kind: "updated"; seq: number; job: JobSnapshot } | 
/**  Job vừa commit xong — `session_id` khớp đúng id đã cấp lúc tạo Job. */
{ kind: "result"; seq: number; jobId: string; sessionId: string } | 
/**
 *  Job kết thúc lỗi hệ thống (Auth/Model/Consent/đọc nguồn/DB) trước khi
 *  commit — không có dòng DB nào được tạo.
 */
{ kind: "error"; seq: number; jobId: string; error: AppError } | 
/**  Job bị huỷ (đang chờ trong hàng, hoặc đang chạy) trước khi commit. */
{ kind: "cancelled"; seq: number; jobId: string };

/**
 *  Ảnh chụp một Job tại một thời điểm — đủ để UI vẽ "32 / 90 phút · 36 %",
 *  Chunk hiện tại, key thứ mấy, số lần thử, và cờ "đang chờ quota" (spec
 *  Tasks: trang Session).
 */
export type JobSnapshot = {
	jobId: string,
	sessionId: string,
	sourceName: string | null,
	state: JobState,
	processedMs: number,
	totalMs: number,
	chunkIndex: number,
	chunkCount: number,
	keyOrdinal: number | null,
	attempt: number | null,
	waitingQuota: boolean,
};

/**
 *  Trạng thái hiển thị của một Job còn trong registry. Một Job biến mất khỏi
 *  registry (và khỏi mọi `JobSnapshot` sau đó) ngay khi nó kết thúc — thành
 *  công, lỗi, hay bị huỷ — nên không có biến thể "hoàn tất"/"lỗi"/"đã huỷ"
 *  ở đây (spec Boundaries: "Không bảng `jobs`, không khôi phục Job sau
 *  restart").
 */
export type JobState = "queued" | "running";

/**
 *  An opaque identifier for one stored API key. The secret is never part of
 *  this value; IDs are UUIDv7 so they are safe to pass through IPC and logs.
 */
export type KeyId = string;

/**
 *  Metadata safe to return to the frontend. `label` is intentionally masked;
 *  neither this type nor its serialized representation contains the
 *  credential itself.
 */
export type KeyMetadata = {
	id: KeyId,
	label: string,
};

export type KeyTestResult = {
	keyId: KeyId,
	valid: boolean,
};

/**  Safe model metadata returned to the frontend and later feature modules. */
export type ModelInfo = {
	name: string,
	displayName: string,
	supportedGenerationMethods: string[],
};

/**
 *  Model families exposed to the rest of the application. Filtering is
 *  performed from API capability metadata, never from a model alias/name.
 */
export type ModelKind = "transcribe" | "live" | "memo";

/**
 *  Kết quả tra `id` của route `/session/:id` — có thể là Job đang chạy/chờ
 *  (registry cấp `session_id` trước khi commit), một Phiên đã lưu, hay không
 *  còn gì (spec I/O Matrix "`/session/:id`").
 */
export type SessionLookup = { kind: "job"; jobId: string; sessionId: string } | { kind: "session"; sessionId: string; title: string; durationSec: number | null; status: string } | { kind: "notFound" };

export type Settings = {
	theme: Theme,
	uiLanguage: UiLanguage,
	onboardingCompleted: boolean,
	/**
	 *  The only consent version the user has accepted. `0` means never
	 *  accepted; this is intentionally independent from `consent_declined`.
	 */
	consentAcceptedVersion: number,
	/**
	 *  A separate decision bit lets the router distinguish a deliberate
	 *  decline from a first-run pending state.
	 */
	consentDeclined: boolean,
	/**
	 *  Free-text model name used by file transcription. Never validated
	 *  against a loaded model list (spec Always: "Tên không có trong danh
	 *  sách đã tải vẫn lưu được"); only non-empty-after-trim is enforced.
	 */
	transcribeModel: string,
	/**  Free-text model name used by Live. */
	liveModel: string,
	/**  Free-text model name used by Memo. */
	memoModel: string,
};

/**
 *  Phát khi `save` ghi bền thành công — đúng một lần, mang giá trị mới toàn
 *  bộ (không phát khi ghi lỗi, spec I/O Matrix).
 */
export type SettingsChanged = Settings;

/**  `theme: 'system' | 'light' | 'dark'`, mặc định `system` (spec Decisions). */
export type Theme = "system" | "light" | "dark";

/**
 *  Kết quả `transcribe_start` (spec Always: thứ tự gate "Consent → hash + tra
 *  `source_hash` → có key dùng được → tạo Job").
 */
export type TranscribeStartOutcome = { kind: "job"; jobId: string; sessionId: string } | { kind: "existing"; sessionId: string };

/**
 *  Preference ngôn ngữ UI. `System` resolve ở frontend từ locale của WebView;
 *  Rust chỉ sở hữu giá trị persisted và không đoán locale hệ điều hành.
 */
export type UiLanguage = "system" | "vi" | "en" | "ja";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

