// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Trả về version của app. Nguồn duy nhất là `Cargo.toml`
	 *  (`CARGO_PKG_VERSION`, đọc lúc biên dịch) — không có nơi thứ hai giữ version.
	 */
	appVersion: () => typedError<string, AppError>(__TAURI_INVOKE("app_version")),
	/**  Đọc toàn bộ settings hiện tại — xem [`get_settings`] cho logic thật. */
	settingsGet: () => typedError<Settings, AppError>(__TAURI_INVOKE("settings_get")),
	/**
	 *  Ghi toàn bộ settings và phát `settingsChanged` — xem
	 *  [`save_settings_and_notify`] cho logic ghi/thông báo thật; phát event
	 *  thất bại (ví dụ chưa có cửa sổ nào) không làm command trả lỗi vì dữ liệu
	 *  đã ghi bền xong, chỉ log cảnh báo.
	 */
	settingsSave: (settings: Settings) => typedError<null, AppError>(__TAURI_INVOKE("settings_save", { settings })),
	/**
	 *  Return the Rust-owned consent policy and the durable decision in one
	 *  typed snapshot. A policy read failure is a storage error; no fallback
	 *  version is invented in the frontend.
	 */
	consentPolicy: () => typedError<ConsentPolicy, AppError>(__TAURI_INVOKE("consent_policy")),
	/**
	 *  Persist acceptance at the current Rust-owned version and emit the full
	 *  settings snapshot only after the durable write succeeds.
	 */
	consentAccept: (settings: Settings) => typedError<Settings, AppError>(__TAURI_INVOKE("consent_accept", { settings })),
	/**
	 *  Persist a deliberate decline independently from the accepted-version
	 *  field, then emit the same full snapshot contract as settings_save.
	 */
	consentDecline: (settings: Settings) => typedError<Settings, AppError>(__TAURI_INVOKE("consent_decline", { settings })),
	/**  Return only opaque IDs and masked labels; key material never crosses IPC. */
	keysList: () => typedError<KeyMetadata[], AppError>(__TAURI_INVOKE("keys_list")),
	/**
	 *  Replace the complete native-store key list, then refresh the actor before
	 *  replying so no removed key can be allocated after command completion.
	 */
	keysSet: (keys: string) => typedError<KeyMetadata[], AppError>(__TAURI_INVOKE("keys_set", { keys })),
	/**  Delete one native credential entry by opaque ID and invalidate old leases. */
	keysDelete: (id: KeyId) => typedError<KeyMetadata[], AppError>(__TAURI_INVOKE("keys_delete", { id })),
	/**
	 *  List models through the one Gemini gateway. Consent is read server-side
	 *  for every call so a stale frontend snapshot can never open transport.
	 */
	modelsList: (kind: ModelKind) => typedError<ModelInfo[], AppError>(__TAURI_INVOKE("models_list", { kind })),
	/**
	 *  Validate one opaque key ID through a target-key lease. The actor path
	 *  deliberately cannot fall back to another key after a 401/403 or quota.
	 */
	keysTest: (id: KeyId) => typedError<KeyTestResult, AppError>(__TAURI_INVOKE("keys_test", { id })),
	/**
	 *  Đọc bộ đếm cục bộ (phiên, lỗi theo category, crash) cho Settings → Chẩn
	 *  đoán — xem [`diagnostics::summary`] cho logic thật.
	 */
	diagnosticsSummary: () => typedError<DiagnosticsSummary, AppError>(__TAURI_INVOKE("diagnostics_summary")),
	/**
	 *  Xoá nhật ký allow-list: file cũ bị xoá, file hôm nay bị truncate (spec
	 *  Boundaries "Xoá nhật ký") — xem [`diagnostics::clear_logs`].
	 */
	diagnosticsClearLogs: () => typedError<null, AppError>(__TAURI_INVOKE("diagnostics_clear_logs")),
	/**
	 *  Xuất gói chẩn đoán: build bundle (log allow-list + bộ đếm) rồi mở dialog
	 *  lưu hệ thống trong `spawn_blocking` — bản thân dialog chạy trên main
	 *  thread qua [`save_diagnostics_bundle`], `spawn_blocking` ở đây chỉ giữ
	 *  việc chờ kết quả tránh chặn runtime async.
	 */
	diagnosticsExport: () => typedError<boolean, AppError>(__TAURI_INVOKE("diagnostics_export")),
	/**
	 *  Bắt đầu transcribe một file (spec Always: thứ tự gate đầy đủ nằm ở
	 *  [`transcribe_start_inner`]). `path` là đường dẫn tuyệt đối do caller cung
	 *  cấp — frontend tự dồn mọi đường vào (dialog `transcribe_pick_files`, kéo
	 *  thả) về một hàng xử lý tuần tự gọi lệnh này từng file (spec 2.8 Approach).
	 */
	transcribeStart: (path: string) => typedError<TranscribeStartOutcome, AppError>(__TAURI_INVOKE("transcribe_start", { path })),
	/**
	 *  Command IPC cho [`pick_source_files`] — trả `Vec<String>` rỗng khi huỷ
	 *  dialog (spec I/O Matrix "Chọn file": "Huỷ dialog → không làm gì").
	 */
	transcribePickFiles: () => typedError<string[], AppError>(__TAURI_INVOKE("transcribe_pick_files")),
	/**
	 *  Chạy lại: vá vùng thiếu, một gap cụ thể, hoặc toàn bộ transcript
	 *  `primary` của một Phiên (spec Approach). `session_id`/`transcript_id` là
	 *  kiểu đã kiểm định dạng qua IPC (giống `jobs_cancel(job_id: JobId)`) — gate
	 *  order thật nằm ở [`decide_transcribe_rerun`].
	 */
	transcribeRerun: (sessionId: string, transcriptId: string, scope: RerunScope) => typedError<TranscribeRerunOutcome, AppError>(__TAURI_INVOKE("transcribe_rerun", { sessionId, transcriptId, scope })),
	/**
	 *  Đăng ký một Channel nhận snapshot rồi các `JobEvent` tiếp theo (spec
	 *  Always: "snapshot và đăng ký Channel trong cùng một lệnh actor").
	 */
	jobsSubscribe: (onEvent: Channel<JobEvent>) => typedError<null, AppError>(__TAURI_INVOKE("jobs_subscribe", { onEvent })),
	/**
	 *  Gỡ đăng ký một Channel đã `jobs_subscribe` trước đó, theo `channel_id`
	 *  (`Channel::id()` phía frontend) — spec Always: "`jobs_unsubscribe`... gỡ
	 *  subscriber có `Channel::id()` khớp"; idempotent, `channel_id` không tồn
	 *  tại vẫn `Ok`.
	 */
	jobsUnsubscribe: (channelId: number) => typedError<null, AppError>(__TAURI_INVOKE("jobs_unsubscribe", { channelId })),
	/**
	 *  Huỷ một Job — xem [`crate::transcribe::job::CancelOutcome`] cho ý nghĩa
	 *  kết quả (spec I/O Matrix "Huỷ": "Cancel đến sau commit -> trả kết quả
	 *  hoàn tất").
	 */
	jobsCancel: (jobId: string) => typedError<CancelOutcome, AppError>(__TAURI_INVOKE("jobs_cancel", { jobId })),
	/**  Tra `id` (Job hoặc Phiên) cho route `/session/:id`. */
	librarySessionGet: (id: string) => typedError<SessionLookup, AppError>(__TAURI_INVOKE("library_session_get", { id })),
	/**
	 *  Đọc chi tiết đầy đủ một Phiên cho `/session/:id` (story 2.7) — xem
	 *  [`library::store::get_detail`] cho logic thật. Caller (`Session.svelte`)
	 *  chỉ gọi lệnh này sau khi `library_session_get` đã xác định `id` là một
	 *  Phiên đã lưu, không phải Job đang chạy (spec Design Notes).
	 */
	librarySessionDetail: (sessionId: string) => typedError<{
	sessionId: string,
	kind: string,
	title: string,
	createdAt: number | null,
	durationSec: number | null,
	recovered: boolean,
	sourceName: string | null,
	proxyPath: string | null,
	transcript: TranscriptDetail | null,
	/**
	 *  Tag đang gắn với Phiên này (story 3.2) — tên tăng dần
	 *  (`library::tags::list_for_session`). Không phụ thuộc
	 *  tên/transcript: đổi tên hay Chạy lại không đụng tới danh sách này
	 *  (spec Boundaries Always).
	 */
	tags: TagSummary[],
} | null, AppError>(__TAURI_INVOKE("library_session_detail", { sessionId })),
	/**
	 *  Export the transcript currently selected in Session detail. Rust reads the
	 *  transcript by its opaque ID (including private speaker/gap data), applies
	 *  the display offset, and owns both the system dialog and file write.
	 */
	libraryTranscriptExport: (sessionId: string, transcriptId: string, format: TranscriptExportFormat, offsetSec: number | null, gapLabels: GapLabels) => typedError<TranscriptExportOutcome, AppError>(__TAURI_INVOKE("library_transcript_export", { sessionId, transcriptId, format, offsetSec, gapLabels })),
	/**
	 *  Liệt kê mọi Phiên cho Home (story 2.9): một truy vấn, mới nhất trước, kèm
	 *  `missing_gap_count` (gap `chunk_failed` của transcript `primary`) — xem
	 *  [`repo::sessions::list_for_home`] cho logic đọc thật.
	 */
	librarySessionsList: () => typedError<SessionListItem[], AppError>(__TAURI_INVOKE("library_sessions_list")),
	/**
	 *  Chọn lại file nguồn cho một Phiên `file` đã lưu (spec Approach, FR-15):
	 *  hash file được chọn phải khớp đúng `source_hash` của Phiên trước khi
	 *  publish Proxy mới — xem [`decide_proxy_relink`] cho thứ tự gate thật và
	 *  [`library::store::relink_proxy`] cho logic publish/DB.
	 */
	libraryProxyRelink: (sessionId: string) => typedError<ProxyRelinkOutcome, AppError>(__TAURI_INVOKE("library_proxy_relink", { sessionId })),
	/**
	 *  Đổi tên một Phiên đã lưu (story 3.1, spec Approach "đổi tên inline") — xem
	 *  [`library::store::rename_session`] cho validate/ghi thật. `Ok(None)` khi
	 *  Phiên không còn tồn tại (đã bị xoá đồng thời) — frontend coi như không có
	 *  gì để cập nhật, không phải lỗi.
	 */
	librarySessionRename: (sessionId: string, title: string) => typedError<string | null, AppError>(__TAURI_INVOKE("library_session_rename", { sessionId, title })),
	/**
	 *  Xoá hẳn một Phiên đã lưu (story 3.1, spec Approach): chặn khi
	 *  `JobRegistry.is_busy(session_id)` (outcome `Busy`, không xoá gì) — xem
	 *  [`decide_session_delete`] cho thứ tự gate thật và
	 *  [`library::store::delete_session`] cho logic xoá DB/media.
	 */
	librarySessionDelete: (sessionId: string) => typedError<SessionDeleteOutcome, AppError>(__TAURI_INVOKE("library_session_delete", { sessionId })),
	/**
	 *  Mọi tag kèm số Phiên đang gắn (story 3.2, spec Boundaries: "sắp số phiên
	 *  giảm dần rồi tên") — xem [`library::tags::list_with_counts`] cho logic đọc
	 *  thật.
	 */
	tagsList: () => typedError<TagWithCount[], AppError>(__TAURI_INVOKE("tags_list")),
	/**
	 *  Tạo tag mới hoặc trả về tag đã có cùng `name_key` (story 3.2) — xem
	 *  [`library::tags::create_or_get`] cho chuẩn hoá/validate/idempotent thật.
	 */
	tagsCreate: (name: string) => typedError<TagSummary, AppError>(__TAURI_INVOKE("tags_create", { name })),
	/**
	 *  Gắn một tag cho một Phiên (story 3.2) — chặn khi `session_id` đang bị
	 *  `library_session_delete` xoá (spec Code Map: "guard `is_session_deleting`
	 *  cho attach"), cùng lý do các lệnh khác chạm một Phiên đang xoá dở. Xem
	 *  [`library::tags::attach_tag`] cho validate giới hạn 20/no-op thật.
	 */
	sessionTagsAttach: (sessionId: string, tagId: string) => typedError<null, AppError>(__TAURI_INVOKE("session_tags_attach", { sessionId, tagId })),
	/**  Gỡ một tag khỏi một Phiên (story 3.2) — xem [`library::tags::detach_tag`]. */
	sessionTagsDetach: (sessionId: string, tagId: string) => typedError<null, AppError>(__TAURI_INVOKE("session_tags_detach", { sessionId, tagId })),
	/**
	 *  Xoá hẳn một tag toàn cục, gỡ khỏi mọi Phiên (story 3.2) — xem
	 *  [`library::tags::delete_tag`].
	 */
	tagsDelete: (tagId: string) => typedError<null, AppError>(__TAURI_INVOKE("tags_delete", { tagId })),
	/**
	 *  Đọc ghi chú đã lưu của một Phiên (story 3.5) — `Ok(None)` khi Phiên chưa
	 *  từng có ghi chú (không phải lỗi). Không có guard `is_wiping`/
	 *  `is_session_deleting` -- đọc không xung đột với xoá/wipe (spec Boundaries
	 *  Always chỉ nói `notes_save` bị từ chối).
	 */
	notesGet: (sessionId: string) => typedError<{
	body: string,
	/**
	 *  `i32` không phải `i64` -- cùng lý do `TagWithCount::session_count`:
	 *  specta-typescript cấm xuất kiểu BigInt, và revision (tăng dần theo
	 *  lần gõ dừng của một Phiên) không bao giờ tới gần `i32::MAX`.
	 */
	revision: number,
	/**
	 *  Mili-giây kể từ Unix epoch (UTC), giữ dạng `f64` -- cùng quy ước
	 *  `SessionDetail::created_at` (một mốc thời gian có thể vượt
	 *  `i32::MAX` nhưng vẫn nguyên trong dải số nguyên chính xác của `f64`).
	 */
	updatedAt: number | null,
} | null, AppError>(__TAURI_INVOKE("notes_get", { sessionId })),
	/**
	 *  Lưu ghi chú của một Phiên nếu `revision` mới lớn hơn revision đang lưu
	 *  (story 3.5, spec Boundaries Always) — từ chối khi Phiên đang bị
	 *  `library_session_delete` xoá hoặc đang `library_wipe_all` (cùng khuôn với
	 *  `session_tags_attach`/`tags_create`). Xem [`library::notes::save`] cho
	 *  validate độ dài/upsert có điều kiện thật.
	 */
	notesSave: (sessionId: string, body: string, revision: number) => typedError<NotesSaveOutcome, AppError>(__TAURI_INVOKE("notes_save", { sessionId, body, revision })),
	/**
	 *  Số liệu Settings → Lưu trữ (story 3.4) — xem [`library::store::storage_stats`]
	 *  cho logic đo thật (Media đệ quy dưới `media/`, DB = `app.db` +
	 *  `-wal`/`-shm`, số Phiên = số dòng `sessions`).
	 */
	libraryStorageStats: () => typedError<StorageStats, AppError>(__TAURI_INVOKE("library_storage_stats")),
	/**
	 *  Mở `<data_dir>` bằng trình quản lý file của OS (spec Never: "Không mở
	 *  quyền `opener` rộng cho frontend" — gọi thẳng `OpenerExt::open_path` từ
	 *  Rust, frontend chỉ nhận `Result<(), AppError>`, không bao giờ thấy đường
	 *  dẫn thật). Lỗi mở (OS/plugin) trả category `storage` để UI hiện lỗi
	 *  inline (spec Always).
	 */
	libraryOpenDataDir: () => typedError<null, AppError>(__TAURI_INVOKE("library_open_data_dir")),
	/**
	 *  Xoá toàn bộ dữ liệu họp (story 3.4, spec Approach): chặn khi có Job chưa
	 *  kết thúc (outcome `Busy`, không xoá gì) — xem [`decide_wipe_all`] cho thứ
	 *  tự gate thật và [`library::store::wipe_all`] cho logic xoá DB/media thật.
	 */
	libraryWipeAll: () => typedError<WipeAllOutcome, AppError>(__TAURI_INVOKE("library_wipe_all")),
	/**
	 *  Người dùng xác nhận đóng app khi registry đang bận (spec Design Notes:
	 *  "đồng ý → huỷ sạch rồi thoát"): huỷ mọi Job hiện có, chờ tối đa ~4 s để
	 *  mỗi Job dọn xong (huỷ có hiệu lực ≤ 2 s — spec Always), rồi thoát tiến
	 *  trình thật sự bất kể kết quả chờ, vì người dùng đã đồng ý đóng.
	 */
	appCloseConfirm: () => typedError<null, AppError>(__TAURI_INVOKE("app_close_confirm")),
};

/** Events */
export const events = {
	closeRequested: makeEvent<CloseRequested>("close-requested"),
	settingsChanged: makeEvent<SettingsChanged>("settings-changed"),
};

/* Types */
/**
 *  Lỗi thống nhất trả qua mọi command IPC. Serialize `{ category, code,
 *  detailRedacted }` — spec Boundaries.
 */
export type AppError = {
	category: Category,
	code: Code,
	detailRedacted: string,
};

/**
 *  Trả về từ lệnh `jobs_cancel` — phân biệt "đã bắt đầu huỷ" khỏi "Job không
 *  còn để huỷ" (đã commit, hoặc id không tồn tại — spec I/O Matrix "Huỷ":
 *  "Cancel đến sau commit -> trả kết quả hoàn tất").
 */
export type CancelOutcome = "cancelling" | "alreadyFinished";

/**  8 category ổn định hiển thị cho người dùng — spec Boundaries. */
export type Category = "quota" | "auth" | "model" | "network" | "format" | "permission" | "storage" | "blocked";

/**
 *  Phát mỗi khi cửa sổ chính bị yêu cầu đóng (story 3.5, spec Code Map: "đổi
 *  để luôn emit (thêm cờ `busy` vào payload event) và frontend quyết định" --
 *  trước đây chỉ emit khi registry bận, nhánh rảnh thoát thẳng từ Rust, nên
 *  không có chỗ nào chắc chắn chạy để flush ghi chú trước khi đóng). `busy`
 *  phản ánh đúng kết quả `JobRegistryHandle::snapshot` tại thời điểm nhận yêu
 *  cầu đóng: `true` mở dialog Job hiện có (`CloseConfirm`), `false` là tín
 *  hiệu để `appStore` tự flush ghi chú rồi gọi `appCloseConfirm` nếu flush
 *  thành công.
 */
export type CloseRequested = {
	busy: boolean,
};

/**
 *  Mã lỗi kỹ thuật — 12 biến thể, người dùng chốt 2026-09-22. Ánh xạ
 *  `code → category` chỉ định nghĩa ở [`Code::category`], không lặp lại nơi
 *  khác trong codebase.
 */
export type Code = "quota" | "auth" | "model" | "request" | "shape" | "timeout" | "network" | "tls" | "blocked" | "format" | "permission" | "storage" | 
/**
 *  File không có track audio phát được, không có frame, hoặc rỗng —
 *  category vẫn `Format` (spec Code Map: "thêm `Code::NoAudio` (→
 *  `Format`)") nhưng `code` khác `Format` để UI nói đúng câu ("File
 *  không có audio phát được." thay vì "Định dạng không hỗ trợ").
 */
"noaudio";

/**
 *  Rust-owned metadata needed to render the consent step. The accepted
 *  version and declined bit are included so the frontend never needs a
 *  second source of truth or a duplicated version constant.
 */
export type ConsentPolicy = {
	currentVersion: number,
	privacyUrl: string,
	/**
	 *  Support contact URL for Settings → Giới thiệu (spec Always). Carried
	 *  here (rather than a separate command) so it is already loaded
	 *  whenever `settingsStore` fetches the consent policy — including when
	 *  Consent was declined, when About must still show it (spec Always:
	 *  "Hoạt động cả khi Consent bị từ chối").
	 */
	supportUrl: string,
	acceptedVersion: number,
	declined: boolean,
	status: ConsentStatus,
};

/**  The state used by both routing and the Gemini transport gate. */
export type ConsentStatus = "pending" | "declined" | "stale" | "current";

/**
 *  Snapshot chỉ-số hiển thị ở Settings → Chẩn đoán. Không có trường nào mang
 *  nội dung — chỉ số nguyên (spec Boundaries: "Riêng tư của bộ đếm").
 */
export type DiagnosticsSummary = {
	sessions: number,
	crashes: number,
	errorsByCategory: ErrorCategoryCount[],
};

export type ErrorCategoryCount = {
	category: Category,
	count: number,
};

/**
 *  Localized gap notes for the TXT formatter, supplied by the frontend (the
 *  same `session.export.gap*` i18n strings Copy already uses) so the export
 *  note matches the UI language instead of a hard-coded English string.
 */
export type GapLabels = {
	chunkFailed: string,
	disconnected: string,
	unknown: string,
};

/**
 *  Một event của registry — mỗi biến thể mang riêng `seq: u32`, một bộ đếm
 *  đơn điệu dùng chung cho toàn bộ registry, không phải theo từng Job (spec
 *  Always: "`seq: u32` đơn điệu cho cả registry").
 */
export type JobEvent = 
/**
 *  Toàn bộ Job hiện có trong registry — gửi riêng cho một Channel mới
 *  đăng ký ngay khi `jobs_subscribe` được gọi, trước mọi event khác của
 *  đúng Channel đó (spec I/O Matrix "Remount UI").
 */
{ kind: "snapshot"; seq: number; jobs: JobSnapshot[] } | 
/**  Một Job (đang chờ hoặc đang chạy) vừa đổi trạng thái hiển thị. */
{ kind: "updated"; seq: number; job: JobSnapshot } | 
/**  Job vừa commit xong — `session_id` khớp đúng id đã cấp lúc tạo Job. */
{ kind: "result"; seq: number; jobId: string; sessionId: string } | 
/**
 *  Job kết thúc lỗi hệ thống (Auth/Model/Consent/đọc nguồn/DB) trước khi
 *  commit — không có dòng DB nào được tạo.
 */
{ kind: "error"; seq: number; jobId: string; error: AppError } | 
/**  Job bị huỷ (đang chờ trong hàng, hoặc đang chạy) trước khi commit. */
{ kind: "cancelled"; seq: number; jobId: string };

/**
 *  Loại Job trong cùng một hàng đợi `JobRegistry` (story 2.5): transcribe
 *  một file mới, hoặc Chạy lại (vá vùng thiếu/toàn bộ) transcript `primary`
 *  của một Phiên đã có (spec Approach: "Thêm Job loại Chạy lại vào đúng
 *  hàng đợi `JobRegistry`"). Không phải bảng riêng, không hàng đợi thứ hai —
 *  chỉ một cờ trên `JobSnapshot` để UI phân biệt hiển thị.
 */
export type JobKind = "transcribe" | "rerun";

/**
 *  Ảnh chụp một Job tại một thời điểm — đủ để UI vẽ "32 / 90 phút · 36 %",
 *  Chunk hiện tại, key thứ mấy, số lần thử, và cờ "đang chờ quota" (spec
 *  Tasks: trang Session).
 */
export type JobSnapshot = {
	jobId: string,
	sessionId: string,
	sourceName: string | null,
	kind: JobKind,
	state: JobState,
	processedMs: number,
	totalMs: number,
	chunkIndex: number,
	chunkCount: number,
	keyOrdinal: number | null,
	attempt: number | null,
	waitingQuota: boolean,
};

/**
 *  Trạng thái hiển thị của một Job còn trong registry. Một Job biến mất khỏi
 *  registry (và khỏi mọi `JobSnapshot` sau đó) ngay khi nó kết thúc — thành
 *  công, lỗi, hay bị huỷ — nên không có biến thể "hoàn tất"/"lỗi"/"đã huỷ"
 *  ở đây (spec Boundaries: "Không bảng `jobs`, không khôi phục Job sau
 *  restart").
 */
export type JobState = "queued" | "running";

/**
 *  An opaque identifier for one stored API key. The secret is never part of
 *  this value; IDs are UUIDv7 so they are safe to pass through IPC and logs.
 */
export type KeyId = string;

/**
 *  Metadata safe to return to the frontend. `label` is intentionally masked;
 *  neither this type nor its serialized representation contains the
 *  credential itself.
 */
export type KeyMetadata = {
	id: KeyId,
	label: string,
};

export type KeyTestResult = {
	keyId: KeyId,
	valid: boolean,
};

/**  Safe model metadata returned to the frontend and later feature modules. */
export type ModelInfo = {
	name: string,
	displayName: string,
	supportedGenerationMethods: string[],
};

/**
 *  Model families exposed to the rest of the application. Filtering is
 *  performed from API capability metadata, never from a model alias/name.
 */
export type ModelKind = "transcribe" | "live" | "memo";

/**
 *  Ghi chú tại ACK gần nhất -- `body` là `String` công khai qua IPC (spec
 *  Always: "payload IPC là `String`"); `Sensitive<String>` chỉ tồn tại trong
 *  Rust nội bộ (`repo::notes`), không lộ ra kiểu này.
 */
export type NoteSnapshot = {
	body: string,
	/**
	 *  `i32` không phải `i64` -- cùng lý do `TagWithCount::session_count`:
	 *  specta-typescript cấm xuất kiểu BigInt, và revision (tăng dần theo
	 *  lần gõ dừng của một Phiên) không bao giờ tới gần `i32::MAX`.
	 */
	revision: number,
	/**
	 *  Mili-giây kể từ Unix epoch (UTC), giữ dạng `f64` -- cùng quy ước
	 *  `SessionDetail::created_at` (một mốc thời gian có thể vượt
	 *  `i32::MAX` nhưng vẫn nguyên trong dải số nguyên chính xác của `f64`).
	 */
	updatedAt: number | null,
};

/**
 *  Kết quả `notes_save` (spec Boundaries Always). `rename_all_fields`
 *  khớp quy ước `SessionLookup` (`ipc/mod.rs`) cho enum có biến thể mang dữ
 *  liệu qua IPC.
 */
export type NotesSaveOutcome = { kind: "saved"; revision: number; updatedAt: number | null } | { kind: "stale"; revision: number } | { kind: "notFound" };

/**
 *  Kết quả `library_proxy_relink` (spec I/O Matrix "Chọn lại khớp/sai/huỷ",
 *  "Phiên live thiếu Proxy"). `LiveUnsupported` gộp cả nhánh Phiên `live`
 *  (chặn trước khi mở dialog) lẫn `library::store::RelinkOutcome::
 *  NotFileSession` (một Phiên `file` bất thường không có `source_hash`) —
 *  cả hai đều báo cùng một thông điệp "chưa có Recording để tái tạo" phía
 *  UI (spec I/O Matrix "Phiên live thiếu Proxy").
 */
export type ProxyRelinkOutcome = "relinked" | "hashMismatch" | "cancelled" | "liveUnsupported";

/**
 *  Phạm vi Chạy lại nhận từ `transcribe_rerun` (spec Approach: `scope ∈
 *  {missing, all, gap(gap_id)}`). `gap_id` là `idx` của Segment gap trong
 *  đúng `transcript_id` -- không phải một range do UI tự tính.
 */
export type RerunScope = { kind: "missing" } | { kind: "all" } | 
/**
 *  `gap_id` is a Segment `idx` (spec Always) — `i32` at the IPC boundary
 *  (specta-typescript forbids exporting BigInt-style `i64`, see
 *  `ipc/spike_channel.rs`); no transcript ever has anywhere close to
 *  `i32::MAX` segments, so the narrowing is lossless in practice.
 */
{ kind: "gap"; gapId: number };

/**
 *  Một đoạn (Segment) đã chuẩn hoá cho `/session/:id` (story 2.7) — không có
 *  `speaker` (spec Boundaries: "Speaker không hiển thị"). `kind`/`gap_reason`
 *  giữ nguyên chuỗi thô khớp `segments::SegmentKind`/`GapReason` (cùng quy
 *  ước với `SessionLookup::Session.status` — chuỗi thô thay vì một enum
 *  specta riêng cho giá trị chỉ dùng để hiển thị).
 */
export type SegmentDetail = {
	/**
	 *  `i32` không phải `i64` — specta-typescript cấm xuất kiểu BigInt (xem
	 *  `transcribe::rerun::RerunScope::Gap::gap_id`, cùng lý do: không
	 *  transcript nào tới gần `i32::MAX` segment). Đây cũng chính là
	 *  `gap_id` mà `transcribe_rerun` mong đợi cho dòng gap này.
	 */
	idx: number,
	startSec: number | null,
	endSec: number | null,
	kind: string,
	gapReason: string | null,
	text: string,
};

/**
 *  Kết quả `library_session_delete` (spec I/O Matrix "Xoá phiên rảnh", "Xoá
 *  khi có Job").
 */
export type SessionDeleteOutcome = "deleted" | "busy";

/**
 *  Chi tiết đầy đủ một Phiên cho `/session/:id` (story 2.7, Task:
 *  "`SessionDetail { session_id, kind, title, created_at, duration_sec,
 *  recovered, source_name, proxy_path, transcript }`"). `proxy_path` là
 *  `Some` chỉ khi `proxy_ext` có giá trị **và** file thật còn tồn tại trên
 *  đĩa — Proxy lỗi hoặc thiếu (spec I/O Matrix "Proxy thiếu") luôn là `None`,
 *  không bao giờ một đường dẫn trỏ tới file không tồn tại. Giữ dạng `String`
 *  (đường dẫn tuyệt đối) thay vì `PathBuf` để khớp quy ước sẵn có của mọi
 *  đường dẫn khác qua IPC trong codebase này (`transcribe_start(path:
 *  String)`). `source_hash` cố ý không nằm trong struct này — so khớp hash
 *  chỉ diễn ra phía Rust ở [`relink_proxy`], frontend không bao giờ thấy
 *  hash. `created_at` là mili-giây kể từ Unix epoch (UTC), giữ dạng `f64`
 *  (không phải `i64`) vì specta-typescript cấm xuất kiểu BigInt (cùng lý do
 *  `SegmentDetail::idx` dùng `i32`) — số nguyên tới 2^53 vẫn chính xác tuyệt
 *  đối trong `f64`, xa hơn nhiều so với bất kỳ mốc thời gian thật nào.
 */
export type SessionDetail = {
	sessionId: string,
	kind: string,
	title: string,
	createdAt: number | null,
	durationSec: number | null,
	recovered: boolean,
	sourceName: string | null,
	proxyPath: string | null,
	transcript: TranscriptDetail | null,
	/**
	 *  Tag đang gắn với Phiên này (story 3.2) — tên tăng dần
	 *  (`library::tags::list_for_session`). Không phụ thuộc
	 *  tên/transcript: đổi tên hay Chạy lại không đụng tới danh sách này
	 *  (spec Boundaries Always).
	 */
	tags: TagSummary[],
};

/**
 *  Một dòng phiên cho danh sách Home (story 2.9) — xem
 *  [`repo::sessions::SessionListRow`] cho logic đọc thật. `created_at` giữ
 *  dạng `f64` (mili-giây epoch, UTC) chứ không phải `i64`, cùng lý do
 *  `SessionDetail::created_at`: specta-typescript cấm xuất kiểu BigInt.
 *  `missing_gap_count` là `i32` (không phải `i64`), cùng lý do
 *  `SegmentDetail::idx` — không Phiên nào tới gần `i32::MAX` gap. `tag_ids`
 *  (story 3.2) là mọi tag đang gắn với Phiên — frontend tra tên qua
 *  `tagsStore`/`tags_list` đã tải riêng, không kèm tên ở đây.
 */
export type SessionListItem = {
	sessionId: string,
	kind: string,
	title: string,
	createdAt: number | null,
	durationSec: number | null,
	recovered: boolean,
	missingGapCount: number,
	tagIds: string[],
};

/**
 *  Kết quả tra `id` của route `/session/:id` — có thể là Job đang chạy/chờ
 *  (registry cấp `session_id` trước khi commit), một Phiên đã lưu, hay không
 *  còn gì (spec I/O Matrix "`/session/:id`").
 */
export type SessionLookup = { kind: "job"; jobId: string; sessionId: string } | { kind: "session"; sessionId: string; title: string; durationSec: number | null; status: string; 
/**
 *  `true` khi transcript `primary` hiện tại còn gap `chunk_failed`
 *  (story 2.5) — điều khiển cảnh báo + nút "Chạy lại phần thiếu" ở
 *  `/session/:id`.
 */
partial: boolean; transcriptId: string | null } | { kind: "notFound" };

export type Settings = {
	theme: Theme,
	uiLanguage: UiLanguage,
	onboardingCompleted: boolean,
	/**
	 *  The only consent version the user has accepted. `0` means never
	 *  accepted; this is intentionally independent from `consent_declined`.
	 */
	consentAcceptedVersion: number,
	/**
	 *  A separate decision bit lets the router distinguish a deliberate
	 *  decline from a first-run pending state.
	 */
	consentDeclined: boolean,
	/**
	 *  Free-text model name used by file transcription. Never validated
	 *  against a loaded model list (spec Always: "Tên không có trong danh
	 *  sách đã tải vẫn lưu được"); only non-empty-after-trim is enforced.
	 */
	transcribeModel: string,
	/**  Free-text model name used by Live. */
	liveModel: string,
	/**  Free-text model name used by Memo. */
	memoModel: string,
	/**
	 *  Độ dài Chunk khi transcribe file (phút), số nguyên >= 1 (spec
	 *  Boundaries Always). Job chụp giá trị này lúc nhận Job
	 *  (`transcribe_start`/`transcribe_rerun`) -- đổi Settings giữa chừng
	 *  không ảnh hưởng Job đang chạy/chờ.
	 */
	chunkMinutes: number,
	/**
	 *  Offset cộng vào timestamp hiển thị/export (giây), số nguyên >= 0 --
	 *  không có offset âm (spec quyết định). Thuần hiển thị: không bao giờ
	 *  ghi vào Segment/DB (spec Always) -- chỉ đọc qua `src/lib/time.ts` ở
	 *  frontend.
	 */
	timestampOffsetSec: number,
	/**
	 *  Ngôn ngữ transcribe file/Live (không phải ngôn ngữ UI). Job chụp cùng
	 *  lúc với `chunk_minutes`/`model`.
	 */
	transcribeLanguage: TranscribeLanguage,
};

/**
 *  Phát khi `save` ghi bền thành công — đúng một lần, mang giá trị mới toàn
 *  bộ (không phát khi ghi lỗi, spec I/O Matrix).
 */
export type SettingsChanged = Settings;

/**
 *  Số liệu Settings → Lưu trữ (story 3.4, spec Always): `media_bytes` là
 *  tổng byte đệ quy dưới `<root>/media/`, `db_bytes` là tổng `app.db` +
 *  `app.db-wal` + `app.db-shm` (file thiếu tính `0`), `session_count` là số
 *  dòng `sessions`. `media_bytes`/`db_bytes` giữ dạng `f64` chứ không phải
 *  `i64` -- cùng lý do `SessionListItem::created_at`: specta-typescript cấm
 *  xuất kiểu BigInt, và `f64` biểu diễn chính xác mọi số nguyên byte tới
 *  2^53 (~8 PB), thừa cho một thư mục dữ liệu người dùng cục bộ.
 *  `session_count` là `i32` (không phải `i64`), cùng quy ước
 *  `SessionListItem::missing_gap_count`.
 */
export type StorageStats = {
	mediaBytes: number | null,
	dbBytes: number | null,
	sessionCount: number,
};

/**
 *  Tag tối giản (id + tên) — dùng cho `tags_create` và `SessionDetail::tags`
 *  (spec Code Map).
 */
export type TagSummary = {
	id: string,
	name: string,
};

/**
 *  Tag kèm số Phiên đang gắn — dùng cho `tags_list` (spec Boundaries: "trả
 *  tag kèm số phiên, sắp số phiên giảm dần rồi tên"). `session_count` là
 *  `i32` (không phải `i64`), cùng quy ước với `SessionListItem::
 *  missing_gap_count` — specta-typescript cấm xuất kiểu BigInt.
 */
export type TagWithCount = {
	id: string,
	name: string,
	sessionCount: number,
};

/**  `theme: 'system' | 'light' | 'dark'`, mặc định `system` (spec Decisions). */
export type Theme = "system" | "light" | "dark";

/**
 *  Ngôn ngữ transcribe (story 2.6, không phải ngôn ngữ UI): `Auto` giữ
 *  nguyên hành vi tự phát hiện hiện có (prompt/request JSON byte-for-byte
 *  không đổi — spec Always); `Ja|Vi|En` thêm một câu chỉ định ngôn ngữ chính
 *  vào prompt (spec `transcribe::adapter::build_general_request`).
 */
export type TranscribeLanguage = "auto" | "ja" | "vi" | "en";

/**
 *  Kết quả `transcribe_rerun` (spec I/O Matrix "Chạy lại `missing`/`gap(id)`/
 *  `all`", "Không có gì để chạy", "Gọi trùng").
 */
export type TranscribeRerunOutcome = { kind: "started"; jobId: string } | { kind: "existing"; jobId: string } | 
/**
 *  The session already has an in-flight rerun targeting a different
 *  `transcript_id`/`ranges` -- no second Job was enqueued (spec Always:
 *  "Never enqueue a second rerun for the same session"). The frontend
 *  treats this like an error notice, not a success.
 */
{ kind: "busy"; jobId: string } | { kind: "nothingToRerun" };

/**
 *  Kết quả `transcribe_start` (spec Always: thứ tự gate "Consent → đuôi file
 *  thuộc allow-list → hash + tra `source_hash` trong DB → tra reservation
 *  JobRegistry → probe → có key dùng được → tạo Job").
 */
export type TranscribeStartOutcome = { kind: "job"; jobId: string; sessionId: string } | { kind: "existing"; sessionId: string } | 
/**
 *  Cùng nội dung (`source_hash`) đã có một Job Transcribe đang chờ/chạy,
 *  chưa commit thành Phiên — mở view Job đó thay vì tạo Job thứ hai
 *  (spec Always: "tra reservation JobRegistry (trùng → `ExistingJob`)").
 */
{ kind: "existingJob"; jobId: string; sessionId: string };

/**
 *  Transcript `primary` (hoặc `retranscribe`, giữ tổng quát) của một Phiên
 *  cho `/session/:id` (story 2.7).
 */
export type TranscriptDetail = {
	id: string,
	variant: string,
	status: string,
	model: string,
	language: string | null,
	segments: SegmentDetail[],
};

export type TranscriptExportFormat = "txt" | "srt" | "json";

export type TranscriptExportOutcome = {
	saved: boolean,
	hasGaps: boolean,
};

/**
 *  Preference ngôn ngữ UI. `System` resolve ở frontend từ locale của WebView;
 *  Rust chỉ sở hữu giá trị persisted và không đoán locale hệ điều hành.
 */
export type UiLanguage = "system" | "vi" | "en" | "ja";

/**
 *  Kết quả `library_wipe_all` (spec I/O Matrix "Xoá thành công", "Đang có
 *  Job").
 */
export type WipeAllOutcome = "wiped" | "busy";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

